# Generated by Django 5.1.1 on 2024-10-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
